name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Generate Release Notes
        run: |
          echo "# Release Notes" > RELEASE_NOTES.md
          echo "## Changes since last release" >> RELEASE_NOTES.md
          echo "### Commit History" >> RELEASE_NOTES.md
          git log $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD~10)..HEAD --pretty=format:"* **%h** - %s%n  > %aD by %aN%n  > %b%n" >> RELEASE_NOTES.md
          echo -e "\n### Build Information" >> RELEASE_NOTES.md
          echo "* Build Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> RELEASE_NOTES.md
          echo "* Git Branch: $(git rev-parse --abbrev-ref HEAD)" >> RELEASE_NOTES.md
          echo "* Git Commit: $(git rev-parse HEAD)" >> RELEASE_NOTES.md

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          name: main-git
          tag_name: main-git
          body_path: RELEASE_NOTES.md
          prerelease: true
          files: |
            target/release/gh-spray
            target/release/gh-spray.exe
          token: ${{ secrets.GITHUB_TOKEN }}
